import Header from "@/components/Header";
import "./globals.css";
import localFont from "next/font/local";

// JetBrains Font
const jetBrain = localFont({
  src: "../fonts/JetBrainsMono-Regular.woff2",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetBrain.className}>
        <div className="wrapper">
          <Header />
          <section className="middle">
            <nav className="box">Nav</nav>
            <main className="box">Main Content</main>
            <aside className="box">Ad unit</aside>
          </section>
          <footer className="box">Footer</footer>
        </div>
      </body>
    </html>
  );
}
